# Generated by Django 5.2.1 on 2025-07-13 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('etiqueta', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='ETIQUETA')),
                ('numero_autorizacao', models.CharField(max_length=20, verbose_name='NÚMERO DE AUTORIZAÇÃO')),
                ('data_solicitacao', models.DateField(verbose_name='DATA DA SOLICITAÇÃO')),
                ('conteudo', models.CharField(default='Sem conteúdo', max_length=200)),
                ('quantidade', models.IntegerField(verbose_name='QUANTIDADE')),
                ('motivo', models.CharField(max_length=100, verbose_name='MOTIVO')),
            ],
            options={
                'verbose_name': 'envio',
                'verbose_name_plural': 'envios',
                'db_table': 'envio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(db_column='CNPJ', max_length=18, unique=True, verbose_name='CNPJ')),
                ('centro_custo', models.IntegerField(verbose_name='CENTRO DE CUSTO')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('bairro', models.CharField(max_length=50, verbose_name='BAIRRO')),
                ('rua', models.CharField(max_length=100, verbose_name='RUA')),
                ('numero', models.CharField(max_length=10, verbose_name='NÚMERO')),
                ('shopping', models.CharField(blank=True, max_length=100, null=True, verbose_name='SHOPPING')),
                ('cidade', models.CharField(max_length=50, verbose_name='CIDADE')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='ESTADO')),
                ('regional', models.CharField(blank=True, max_length=2, null=True, verbose_name='REGIONAL')),
                ('numero_unidade', models.CharField(blank=True, max_length=10, null=True, verbose_name='NUMERO DA UNIDADE')),
                ('empresa', models.CharField(blank=True, max_length=50, null=True, verbose_name='EMPRESA')),
            ],
            options={
                'verbose_name': 'unidade',
                'verbose_name_plural': 'unidades',
                'db_table': 'unidade',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rateio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fatura', models.CharField(blank=True, max_length=20, null=True, verbose_name='FATURA')),
                ('etiqueta_original', models.CharField(max_length=50, verbose_name='ETIQUETA')),
                ('titular_cartao', models.CharField(blank=True, max_length=100, null=True, verbose_name='TITULAR CARTÃO')),
                ('servico', models.CharField(blank=True, max_length=100, null=True, verbose_name='SERVIÇO')),
                ('data_postagem', models.DateField(blank=True, null=True, verbose_name='DATA DA POSTAGEM')),
                ('unidade_postagem', models.CharField(blank=True, max_length=100, null=True, verbose_name='UNIDADE POSTAGEM')),
                ('valor_declarado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='VALOR DECLARADO')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='VALOR UNITÁRIO')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='PESO')),
                ('servico_adicionais', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='SERVIÇOS ADICIONAIS')),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DESCONTO')),
                ('valor_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='VALOR LIQUIDO')),
                ('etiqueta', models.ForeignKey(blank=True, db_column='etiqueta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='SRCs.envio', verbose_name='ETIQUETA')),
            ],
            options={
                'verbose_name': 'rateio',
                'verbose_name_plural': 'rateios',
                'db_table': 'rateio',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='envio',
            name='destinatario',
            field=models.ForeignKey(db_column='destinatario', on_delete=django.db.models.deletion.DO_NOTHING, related_name='envio_destinatario_set', to='SRCs.unidade', verbose_name='DESTINATÁRIO'),
        ),
        migrations.AddField(
            model_name='envio',
            name='remetente',
            field=models.ForeignKey(db_column='remetente', on_delete=django.db.models.deletion.DO_NOTHING, to='SRCs.unidade', verbose_name='REMETENTE'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartao_postagem', models.CharField(max_length=30, verbose_name='CARTÃO POSTAGEM')),
                ('perfil', models.CharField(choices=[('Admin', 'Admin'), ('Analista', 'Analista'), ('Basic', 'Basic'), ('Supervisor', 'Supervisor')], default='basic', max_length=10, verbose_name='TIPO PERFIL')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='envio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SRCs.usuario', verbose_name='USUÁRIO'),
        ),
    ]
