# Generated by Django 5.2.1 on 2025-08-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRCs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='id_visual',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID Visual'),
        ),
    ]
