# Generated by Django 5.2.1 on 2025-06-09 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SRCs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
