# Generated by Django 5.2.1 on 2025-10-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRCs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CÓDIGO DE RASTREIO'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='numero_autorizacao',
            field=models.CharField(max_length=20, verbose_name='CÓDIGO DE POSTAGEM'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='bairro',
            field=models.CharField(max_length=50, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='centro_custo',
            field=models.IntegerField(verbose_name='Centro de custo'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='cidade',
            field=models.CharField(max_length=50, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='empresa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='numero_unidade',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número da unidade'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='regional',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Regional'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='rua',
            field=models.CharField(max_length=100, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='shopping',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shopping'),
        ),
    ]
