# Generated by Django 5.2.1 on 2025-11-12 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRCs', '0002_alter_envio_etiqueta_alter_envio_numero_autorizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateio',
            name='etiqueta',
            field=models.ForeignKey(blank=True, db_column='etiqueta', null=True, on_delete=django.db.models.deletion.CASCADE, to='SRCs.envio', verbose_name='ETIQUETA'),
        ),
    ]
