# Generated by Django 5.2.1 on 2025-07-02 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SRCs', '0002_delete_produto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envio',
            options={'managed': True, 'verbose_name': 'envio', 'verbose_name_plural': 'envios'},
        ),
        migrations.AlterModelOptions(
            name='rateio',
            options={'managed': True, 'verbose_name': 'rateio', 'verbose_name_plural': 'rateios'},
        ),
        migrations.AlterModelOptions(
            name='unidade',
            options={'managed': True, 'verbose_name': 'unidade', 'verbose_name_plural': 'unidades'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True, 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
