# Generated by Django 5.2.1 on 2025-07-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRCs', '0002_criar_permissoes_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='cnpj',
            field=models.CharField(db_column='CNPJ', max_length=18, verbose_name='CNPJ'),
        ),
    ]
