# Generated by Django 5.2.1 on 2025-08-10 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRCs', '0002_envio_id_visual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='conteudo',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='quantidade',
        ),
        migrations.AlterField(
            model_name='envio',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='envio_destinatario_set', to='SRCs.unidade', verbose_name='DESTINATÁRIO'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SRCs.unidade', verbose_name='REMETENTE'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Analista', 'Analista'), ('Agente', 'Agente'), ('Supervisor', 'Supervisor'), ('Cliente', 'Cliente')], default='Cliente', max_length=15, verbose_name='Perfil'),
        ),
        migrations.CreateModel(
            name='ItemEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(max_length=200, verbose_name='CONTEÚDO')),
                ('quantidade', models.IntegerField(verbose_name='QUANTIDADE')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='VALOR UNITÁRIO')),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='SRCs.envio')),
            ],
        ),
    ]
