# Generated by Django 5.2.1 on 2025-07-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRCs', '0003_alter_unidade_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='cnpj',
            field=models.CharField(db_column='CNPJ', max_length=18, unique=True, verbose_name='CNPJ'),
        ),
    ]
