# Generated by Django 5.2.1 on 2025-08-22 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRCs', '0003_remove_envio_conteudo_remove_envio_quantidade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_usuarios/'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='envios_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='USUÁRIO'),
        ),
    ]
