# Generated by Django 5.2.1 on 2025-07-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRCs', '0004_alter_unidade_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='excluida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='cnpj',
            field=models.CharField(blank=True, db_column='CNPJ', max_length=18, null=True, unique=True, verbose_name='CNPJ'),
        ),
    ]
