# Generated by Django 5.2.1 on 2025-07-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRCs', '0005_unidade_excluida_alter_unidade_cnpj'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True, 'permissions': [('cadastrar_usuario', 'Cadastrar Usuário'), ('editar_usuario', 'Editar Usuário'), ('cadastrar_unidade', 'Cadastrar Unidade'), ('editar_unidade', 'Editar Unidade'), ('cadastrar_envio', 'Cadastrar Envio'), ('consultar_rateio', 'Consultar Rateio'), ('consultar_dashboard', 'Consultar Dashboard'), ('acompanhar_envio', 'Acompanhar Envio')], 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default=12, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
