# Generated by Django 5.2.1 on 2025-07-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRCs', '0008_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
