# Generated by Django 5.2.1 on 2025-07-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SRCs', '0011_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True, 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
    ]
